# Generated by Django 4.2.2 on 2025-08-28 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0003_alter_product_options_product_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_products",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Продукт пользователя",
            ),
            preserve_default=False,
        ),
    ]
